# Generated by Django 5.2.17 on 2026-09-16 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('notifications', '0002_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='audience',
            field=models.CharField(choices=[('all', 'Everyone'), ('faculty', 'Faculty'), ('students', 'Students'), ('department', 'Department'), ('course', 'Course')], db_index=True, default='all', max_length=20),
        ),
    ]
