# Generated by Django 5.2.17 on 2026-09-16 19:02

from django.db import migrations, models
from django.db.models import F
from django.utils import timezone


def mark_past_announcements_delivered(apps, schema_editor):
    # Before this field existed, announcements already live at creation were sent then.
    Announcement = apps.get_model("notifications", "Announcement")
    Announcement.objects.filter(published_at__lte=timezone.now()).update(
        delivered_at=F("published_at")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_announcement_course_alter_announcement_audience"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="delivered_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(mark_past_announcements_delivered, migrations.RunPython.noop),
    ]
