# Generated by Django 5.2.17 on 2026-09-16 15:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('judge0_id', models.PositiveIntegerField(unique=True)),
                ('version', models.CharField(blank=True, max_length=60)),
                ('editor_mode', models.CharField(default='plaintext', help_text='Code editor language id, e.g. python, cpp.', max_length=30)),
                ('default_template', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('statement', models.TextField()),
                ('input_format', models.TextField(blank=True)),
                ('output_format', models.TextField(blank=True)),
                ('constraints', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default='easy', max_length=6)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('time_limit_seconds', models.DecimalField(decimal_places=2, default=Decimal('2'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('15'))])),
                ('memory_limit_kb', models.PositiveIntegerField(default=128000, validators=[django.core.validators.MinValueValidator(2048), django.core.validators.MaxValueValidator(512000)])),
                ('max_score', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
                ('allow_partial', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=10)),
                ('visible_from', models.DateTimeField(blank=True, null=True)),
                ('visible_until', models.DateTimeField(blank=True, null=True)),
                ('allowed_languages', models.ManyToManyField(blank=True, related_name='+', to='coding.language')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='problems_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], db_index=True, default='queued', max_length=10)),
                ('verdict', models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('partial', 'Partially correct'), ('wrong_answer', 'Wrong answer'), ('time_limit', 'Time limit exceeded'), ('memory_limit', 'Memory limit exceeded'), ('runtime_error', 'Runtime error'), ('compile_error', 'Compilation error'), ('internal_error', 'Judge error')], db_index=True, max_length=16)),
                ('score', models.PositiveIntegerField(default=0)),
                ('passed_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('max_time_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('max_memory_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('compile_output', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('judged_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='coding.language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='coding.problem')),
            ],
            options={
                'ordering': ['-submitted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(blank=True)),
                ('expected_output', models.TextField(blank=True)),
                ('is_sample', models.BooleanField(default=False, help_text='Shown in the problem statement.')),
                ('is_hidden', models.BooleanField(default=True, help_text='Input and output never shown.')),
                ('weight', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.PositiveIntegerField(default=0)),
                ('explanation', models.TextField(blank=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='coding.problem')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TestCaseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge0_token', models.CharField(blank=True, max_length=64)),
                ('verdict', models.CharField(choices=[('accepted', 'Accepted'), ('partial', 'Partially correct'), ('wrong_answer', 'Wrong answer'), ('time_limit', 'Time limit exceeded'), ('memory_limit', 'Memory limit exceeded'), ('runtime_error', 'Runtime error'), ('compile_error', 'Compilation error'), ('internal_error', 'Judge error')], max_length=16)),
                ('passed', models.BooleanField(default=False)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('time_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('memory_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='coding.codesubmission')),
                ('test_case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='coding.testcase')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='codesubmission',
            index=models.Index(fields=['problem', 'student', 'submitted_at'], name='coding_code_problem_20c9d7_idx'),
        ),
    ]
