# Generated by Django 5.2.17 on 2026-09-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_backfill_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tokens_valid_after',
            field=models.DateTimeField(blank=True, help_text='Access tokens issued before this moment are rejected.', null=True),
        ),
    ]
